version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src:ro
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - beer-recommendation-db:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: localhost
      ADMINER_DEFAULT_DB_NAME: beer_database
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8080:8080

volumes:
  beer-recommendation-db:
