version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src:ro
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - beer-recommendation-db:/var/lib/mysql

volumes:
  beer-recommendation-db:
