version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src:ro
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - beer-recommendation-db:/var/lib/mysql

volumes:
  beer-recommendation-db: